-- MySQL Script generated by MySQL Workbench
-- Sun Oct  6 22:45:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema opisk_t6ruar00
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema opisk_t6ruar00
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `opisk_t6ruar00` DEFAULT CHARACTER SET utf8 ;
USE `opisk_t6ruar00` ;

-- -----------------------------------------------------
-- Table `opisk_t6ruar00`.`Tuote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opisk_t6ruar00`.`Tuote` ;

CREATE TABLE IF NOT EXISTS `opisk_t6ruar00`.`Tuote` (
  `idtuote` INT NOT NULL,
  `nimi` VARCHAR(45) NULL,
  `hinta` INT NULL,
  PRIMARY KEY (`idtuote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opisk_t6ruar00`.`Asiakas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opisk_t6ruar00`.`Asiakas` ;

CREATE TABLE IF NOT EXISTS `opisk_t6ruar00`.`Asiakas` (
  `idAsiakas` INT NOT NULL AUTO_INCREMENT,
  `nimi` VARCHAR(45) NULL,
  `salasana` VARCHAR(255) NULL,
  PRIMARY KEY (`idAsiakas`),
  UNIQUE INDEX `nimi_UNIQUE` (`nimi` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opisk_t6ruar00`.`Ostoskori`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opisk_t6ruar00`.`Ostoskori` ;

CREATE TABLE IF NOT EXISTS `opisk_t6ruar00`.`Ostoskori` (
  `idOstoskori` INT NOT NULL AUTO_INCREMENT,
  `maara` INT NULL,
  `idAsiakas` INT NOT NULL,
  `idTuote` INT NOT NULL,
  PRIMARY KEY (`idOstoskori`),
  INDEX `idOstoskori_idx` (`idAsiakas` ASC),
  INDEX `idOstoskori1_idx` (`idTuote` ASC),
  CONSTRAINT `idOstoskori`
    FOREIGN KEY (`idAsiakas`)
    REFERENCES `opisk_t6ruar00`.`Asiakas` (`idAsiakas`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idOstoskori1`
    FOREIGN KEY (`idTuote`)
    REFERENCES `opisk_t6ruar00`.`Tuote` (`idtuote`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `opisk_t6ruar00` ;

-- -----------------------------------------------------
-- procedure LisaaOstoskoriin
-- -----------------------------------------------------

USE `opisk_t6ruar00`;
DROP procedure IF EXISTS `opisk_t6ruar00`.`LisaaOstoskoriin`;

DELIMITER $$
USE `opisk_t6ruar00`$$
CREATE PROCEDURE `LisaaOstoskoriin` (
in maara INT,
in nimiIN varchar(45),
in tuoteID int
)
BEGIN
DECLARE asiakasID INT;
select idAsiakas into asiakasID from Asiakas where nimi=nimiIN;

insert into Ostoskori values(null, maara, asiakasID, tuoteID);
END;$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `opisk_t6ruar00`.`Tuote`
-- -----------------------------------------------------
START TRANSACTION;
USE `opisk_t6ruar00`;
INSERT INTO `opisk_t6ruar00`.`Tuote` (`idtuote`, `nimi`, `hinta`) VALUES (1, 'tekken7', 40);
INSERT INTO `opisk_t6ruar00`.`Tuote` (`idtuote`, `nimi`, `hinta`) VALUES (2, 'mordhau', 25);
INSERT INTO `opisk_t6ruar00`.`Tuote` (`idtuote`, `nimi`, `hinta`) VALUES (3, 'fgo', 0);

COMMIT;
